;;(global-set-key (kbd "C-s") 'save-buffer)
(global-unset-key (kbd "C-z"))
(global-unset-key (kbd "C-s"))
(global-unset-key (kbd "C-S-<f3>"))
(global-set-key (kbd "C-`") 'kill-emacs)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "<C-tab>") 'other-window)
(global-set-key (kbd "C-s") 'save-buffer)
(global-set-key (kbd "C-S-<f3>") 'isearch-forward)
